src/Entity/Admins.php
<?php

namespace App\Entity;

use App\Repository\AdminsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdminsRepository::class)]
class Admins
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $poste;

    #[ORM\Column(type: 'datetime')]
    private $date_debut_fonction;

    #[ORM\Column(type: 'string', length: 255)]
    private $competences;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $cv;

    #[ORM\Column(type: 'text', nullable: true)]
    private $parcours;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $statut;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'admins')]
    #[ORM\JoinColumn(nullable: false)]
    private $possesseur;

    #[ORM\OneToMany(mappedBy: 'admin', targetEntity: Requetes::class)]
    private $requetes;

    #[ORM\OneToMany(mappedBy: 'admin', targetEntity: Matieres::class, orphanRemoval: true)]
    private $matieres;

    public function __construct()
    {
        $this->requetes = new ArrayCollection();
        $this->matieres = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->poste;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): self
    {
        $this->poste = $poste;

        return $this;
    }

    public function getDateDebutFonction(): ?\DateTimeInterface
    {
        return $this->date_debut_fonction;
    }

    public function setDateDebutFonction(\DateTimeInterface $date_debut_fonction): self
    {
        $this->date_debut_fonction = $date_debut_fonction;

        return $this;
    }

    public function getCompetences(): ?string
    {
        return $this->competences;
    }

    public function setCompetences(string $competences): self
    {
        $this->competences = $competences;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }

    public function getParcours(): ?string
    {
        return $this->parcours;
    }

    public function setParcours(?string $parcours): self
    {
        $this->parcours = $parcours;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getPossesseur(): ?User
    {
        return $this->possesseur;
    }

    public function setPossesseur(?User $possesseur): self
    {
        $this->possesseur = $possesseur;

        return $this;
    }

    /**
     * @return Collection<int, Requetes>
     */
    public function getRequetes(): Collection
    {
        return $this->requetes;
    }

    public function addRequete(Requetes $requete): self
    {
        if (!$this->requetes->contains($requete)) {
            $this->requetes[] = $requete;
            $requete->setAdmin($this);
        }

        return $this;
    }

    public function removeRequete(Requetes $requete): self
    {
        if ($this->requetes->removeElement($requete)) {
            // set the owning side to null (unless already changed)
            if ($requete->getAdmin() === $this) {
                $requete->setAdmin(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Matieres>
     */
    public function getMatieres(): Collection
    {
        return $this->matieres;
    }

    public function addMatiere(Matieres $matiere): self
    {
        if (!$this->matieres->contains($matiere)) {
            $this->matieres[] = $matiere;
            $matiere->setAdmin($this);
        }

        return $this;
    }

    public function removeMatiere(Matieres $matiere): self
    {
        if ($this->matieres->removeElement($matiere)) {
            // set the owning side to null (unless already changed)
            if ($matiere->getAdmin() === $this) {
                $matiere->setAdmin(null);
            }
        }

        return $this;
    }
}

src/Controller/CrudAdminController.php
<?php

namespace App\Controller;

use App\Entity\Admins;
use App\Repository\UserRepository;
use App\Form\AdminsType;
use App\Repository\AdminsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/root")
 * @IsGranted("ROLE_ROOT")
 */
#[Route('/crud/admin')]
class CrudAdminController extends AbstractController
{
    #[Route('/', name: 'app_crud_admin_index', methods: ['GET'])]
    public function index(AdminsRepository $adminsRepository): Response
    {
        return $this->render('crud_admin/index.html.twig', [
            'admins' => $adminsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_crud_admin_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AdminsRepository $adminsRepository,UserRepository $userRepo): Response
    {
        $admin = new Admins();
        $admin->setCv('indef');
      
        $form = $this->createForm(AdminsType::class, $admin);
        $form->handleRequest($request);

       
        if ($form->isSubmitted() && $form->isValid()) {

            $user = $userRepo->find($admin->getPossesseur()->getId());
            $user->setRoles(['ROLE_ADMIN']);
    
            $adminsRepository->add($admin);
            return $this->redirectToRoute('app_crud_admin_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('crud_admin/new.html.twig', [
            'admin' => $admin,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_crud_admin_show', methods: ['GET'])]
    public function show(Admins $admin): Response
    {
        return $this->render('crud_admin/show.html.twig', [
            'admin' => $admin,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_crud_admin_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Admins $admin, AdminsRepository $adminsRepository): Response
    {
        $form = $this->createForm(AdminsType::class, $admin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $adminsRepository->add($admin);
            return $this->redirectToRoute('app_crud_admin_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('crud_admin/edit.html.twig', [
            'admin' => $admin,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_crud_admin_delete', methods: ['POST'])]
    public function delete(Request $request, Admins $admin, AdminsRepository $adminsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$admin->getId(), $request->request->get('_token'))) {
            $adminsRepository->remove($admin);
        }

        return $this->redirectToRoute('app_crud_admin_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/crud_admin/_delete_form.html.twig
<form method="post" action="{{ path('app_crud_admin_delete', {'id': admin.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ admin.id) }}">
    <button class="btn">Delete</button>
</form>

templates/crud_admin/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/crud_admin/edit.html.twig
{% extends 'base_root.html.twig' %}

{% block title %}Edit Admins{% endblock %}

{% block body %}
<div>
    <h1>Edit Admins</h1>

    {{ include('crud_admin/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_crud_admin_index') }}">back to list</a>

    {{ include('crud_admin/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/crud_admin/index.html.twig
{% extends 'base_root.html.twig' %}

{% block title %}Admins index{% endblock %}

{% block body %}
<div>
    <h1>Admins index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>User</th>
                <th>User matricule</th>
                <th>Poste</th>
                <th>Date_debut_fonction</th>
                <th>Competences</th>
                <th>Cv</th>
                <th>Parcours</th>
               
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for admin in admins %}
            <tr>
                <td>{{ admin.id }}</td>
                <td>{{ admin.possesseur.nom }} {{admin.possesseur.prenom}}</td>
                <td>{{ admin.possesseur.matricule }}</td>
                <td>{{ admin.poste }}</td>
                <td>{{ admin.dateDebutFonction ? admin.dateDebutFonction|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ admin.competences }}</td>
                <td>{{ admin.cv }}</td>
                <td>{{ admin.parcours }}</td>
               
                <td>{{ admin.statut }}</td>
                <td>
                    <a href="{{ path('app_crud_admin_show', {'id': admin.id}) }}">show</a>
                    <a href="{{ path('app_crud_admin_edit', {'id': admin.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_crud_admin_new') }}">Create new</a>
</div>
{% endblock %}

templates/crud_admin/new.html.twig
{% extends 'base_root.html.twig' %}

{% block title %}New Admins{% endblock %}

{% block body %}
<div>
    <h1>Create new Admins</h1>

    {{ include('crud_admin/_form.html.twig') }}
<hr>
    <a href="{{ path('app_crud_admin_index') }}">back to list</a>

    <br><br>
</div>
{% endblock %}

templates/crud_admin/show.html.twig
{% extends 'base_root.html.twig' %}

{% block title %}Admins{% endblock %}

{% block body %}
<div>
    <h1>Admins</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ admin.id }}</td>
            </tr>

            <tr>
                <th>User</th>
                <td>{{ admin.possesseur.nom }} {{admin.possesseur.prenom}}</td>
            </tr>

            <tr>
                <th>User matricule</th>
                <td>{{ admin.possesseur.matricule }} </td>
            </tr>

            <tr>
                <th>Poste</th>
                <td>{{ admin.poste }}</td>
            </tr>
            <tr>
                <th>Date_debut_fonction</th>
                <td>{{ admin.dateDebutFonction ? admin.dateDebutFonction|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Competences</th>
                <td>{{ admin.competences }}</td>
            </tr>
            <tr>
                <th>Cv</th>
                <td>{{ admin.cv }}</td>
            </tr>
            <tr>
                <th>Parcours</th>
                <td>{{ admin.parcours }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ admin.statut }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_crud_admin_index') }}">back to list</a>

    <a href="{{ path('app_crud_admin_edit', {'id': admin.id}) }}">edit</a>

    {{ include('crud_admin/_delete_form.html.twig') }}
</div>
{% endblock %}