src/Entity/Requetes.php
<?php

namespace App\Entity;

use App\Repository\RequetesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RequetesRepository::class)]
class Requetes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $recu;

    #[ORM\Column(type: 'string', length: 255)]
    private $quitus;

    #[ORM\Column(type: 'string', length: 255)]
    private $objet;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $etat;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $statut;

    #[ORM\ManyToOne(targetEntity: Etudiants::class, inversedBy: 'requetes')]
    #[ORM\JoinColumn(nullable: false)]
    private $etudiant;

    #[ORM\ManyToOne(targetEntity: Admins::class, inversedBy: 'requetes')]
    private $admin;

    #[ORM\ManyToOne(targetEntity: Matieres::class, inversedBy: 'requetes')]
    #[ORM\JoinColumn(nullable: false)]
    private $matiere;

    #[ORM\OneToMany(mappedBy: 'requete', targetEntity: Revendications::class, orphanRemoval: true)]
    private $revendications;

    #[ORM\Column(type: 'datetime')]
    private $date_depot;

    #[ORM\Column(type: 'datetime',nullable: true)]
    private $date_traite;

    public function __construct()
    {
        $this->revendications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRecu(): ?string
    {
        return $this->recu;
    }

    public function setRecu(string $recu): self
    {
        $this->recu = $recu;

        return $this;
    }

    public function getQuitus(): ?string
    {
        return $this->quitus;
    }

    public function setQuitus(string $quitus): self
    {
        $this->quitus = $quitus;

        return $this;
    }

    public function getObjet(): ?string
    {
        return $this->objet;
    }

    public function setObjet(string $objet): self
    {
        $this->objet = $objet;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(?string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getEtudiant(): ?Etudiants
    {
        return $this->etudiant;
    }

    public function setEtudiant(?Etudiants $etudiant): self
    {
        $this->etudiant = $etudiant;

        return $this;
    }

    public function getAdmin(): ?Admins
    {
        return $this->admin;
    }

    public function setAdmin(?Admins $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getMatiere(): ?Matieres
    {
        return $this->matiere;
    }

    public function setMatiere(?Matieres $matiere): self
    {
        $this->matiere = $matiere;

        return $this;
    }

    /**
     * @return Collection<int, Revendications>
     */
    public function getRevendications(): Collection
    {
        return $this->revendications;
    }

    public function addRevendication(Revendications $revendication): self
    {
        if (!$this->revendications->contains($revendication)) {
            $this->revendications[] = $revendication;
            $revendication->setRequete($this);
        }

        return $this;
    }

    public function removeRevendication(Revendications $revendication): self
    {
        if ($this->revendications->removeElement($revendication)) {
            // set the owning side to null (unless already changed)
            if ($revendication->getRequete() === $this) {
                $revendication->setRequete(null);
            }
        }

        return $this;
    }

    public function getDateDepot(): ?\DateTimeInterface
    {
        return $this->date_depot;
    }

    public function setDateDepot(\DateTimeInterface $date_depot): self
    {
        $this->date_depot = $date_depot;

        return $this;
    }

    public function getDateTraite(): ?\DateTimeInterface
    {
        return $this->date_traite;
    }

    public function setDateTraite(\DateTimeInterface $date_traite): self
    {
        $this->date_traite = $date_traite;

        return $this;
    }
}

src/Controller/CrudRequetesController.php
<?php

namespace App\Controller;

use App\Entity\Requetes;
use App\Form\RequetesType;
use App\Repository\EtudiantsRepository;
use App\Repository\RequetesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/crud/requetes')]
class CrudRequetesController extends AbstractController
{
    #[Route('/', name: 'app_crud_requetes_index', methods: ['GET'])]
    public function index(RequetesRepository $requetesRepository, EtudiantsRepository $etudiantRepo): Response
    {
        $etudiant = $etudiantRepo->findOneBy(['possesseur'=>$this->getUser()]);
        return $this->render('crud_requetes/index.html.twig', [
            'requetes' => $requetesRepository->findBy(['etudiant'=>$etudiant]),
        ]);
    }

// -----------------------------------------------------------------------------------------

#[Route('/all', name: 'app_crud_requetes_index_all', methods: ['GET'])]
public function request_all(RequetesRepository $requetesRepository, EtudiantsRepository $etudiantRepo): Response
{
    $etudiant = $etudiantRepo->findOneBy(['possesseur'=>$this->getUser()]);
    return $this->render('crud_requetes/index_all.html.twig', [
        'requetes' => $requetesRepository->findBy(['etat'=>'non aboutis','statut'=>'actif']),
    ]);
}

// -------------------------------------------------------------------------------------------

    #[Route('/new', name: 'app_crud_requetes_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RequetesRepository $requetesRepository, EtudiantsRepository $etudiantRepo): Response
    {
        $requete = new Requetes();

        $form = $this->createForm(RequetesType::class, $requete);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $etudiant = $etudiantRepo->findOneBy(['possesseur'=>$this->getUser()]);
            $requete->setEtudiant($etudiant);
            $requete->setStatut('actif');
            $requete->setEtat('non aboutis');
            $requete->setDateDepot(new \datetime());
            

            $requetesRepository->add($requete);
            return $this->redirectToRoute('app_crud_requetes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('crud_requetes/new.html.twig', [
            'requete' => $requete,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_crud_requetes_show', methods: ['GET'])]
    public function show(Requetes $requete): Response
    {
        return $this->render('crud_requetes/show.html.twig', [
            'requete' => $requete,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_crud_requetes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Requetes $requete, RequetesRepository $requetesRepository): Response
    {
        $form = $this->createForm(RequetesType::class, $requete);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $requetesRepository->add($requete);
            return $this->redirectToRoute('app_crud_requetes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('crud_requetes/edit.html.twig', [
            'requete' => $requete,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_crud_requetes_delete', methods: ['POST'])]
    public function delete(Request $request, Requetes $requete, RequetesRepository $requetesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$requete->getId(), $request->request->get('_token'))) {
            $requetesRepository->remove($requete);
        }

        return $this->redirectToRoute('app_crud_requetes_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/crud_requetes/_delete_form.html.twig
<form method="post" action="{{ path('app_crud_requetes_delete', {'id': requete.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ requete.id) }}">
    <button class="btn">Delete</button>
</form>

templates/crud_requetes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/crud_requetes/edit.html.twig
{% extends 'base_etudiant.html.twig' %}

{% block title %}Edit Requetes{% endblock %}

{% block body %}
<div>
    <h1>Edit Requetes</h1>

    {{ include('crud_requetes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_crud_requetes_index') }}">back to list</a>

    {{ include('crud_requetes/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/crud_requetes/index.html.twig
{% extends 'base_etudiant.html.twig' %}

{% block title %}Requetes index{% endblock %}

{% block body %}
<div>
    <h1>Requetes index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Matiere</th>
                <th>Recu</th>
                <th>Quitus</th>
                <th>Objet</th>
                <th>Description</th>
                <th>Date de dépot</th>
                <th>Etat</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for requete in requetes %}
            <tr>
                <td>{{ requete.id }}</td>
                <td>{{requete.matiere.titre}}</td>
                <td>{{ requete.recu }}</td>
                <td>{{ requete.quitus }}</td>
                <td>{{ requete.objet }}</td>
                <td>{{ requete.description }}</td>
                <td>{{ requete.dateDepot|date("d/n/Y H:i:s") }}</td>
                <td>{{ requete.etat }}</td>
                <td>{{ requete.statut }}</td>
                <td>
                    <a href="{{ path('app_crud_requetes_show', {'id': requete.id}) }}">show</a>
                    
                    <a href="{{ path('app_crud_requetes_edit', {'id': requete.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_crud_requetes_new') }}">Create new</a>
</div>
{% endblock %}

templates/crud_requetes/index_all.html.twig
{% extends 'base_etudiant.html.twig' %}

{% block title %}Requetes index{% endblock %}

{% block body %}
<div>
    <h1>List of requests ({{requetes|length}})</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Etudiant</th>
                <th>Matricule</th>
                <th>Matiere</th>
                <th>Recu</th>
                <th>Quitus</th>
                <th>Objet</th>
                <th>Description</th>
                <th>Date de dépot</th>
                <th>Etat</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for requete in requetes %}
            <tr>
                <td>{{ requete.id }}</td>

                <td>{{ requete.etudiant.possesseur.nom }} {{ requete.etudiant.possesseur.prenom }}</td>
                <td>{{ requete.etudiant.possesseur.matricule }}</td>

                <td>{{requete.matiere.titre}}</td>
                <td>{{ requete.recu }}</td>
                <td>{{ requete.quitus }}</td>
                <td>{{ requete.objet }}</td>
                <td>{{ requete.description }}</td>
                <td>{{ requete.dateDepot|date("d/n/Y H:i:s") }}</td>
                <td>{{ requete.etat }}</td>
                <td>{{ requete.statut }}</td>
                <td>
                    <a href="{{ path('app_crud_requetes_show', {'id': requete.id}) }}">show</a>
                    
                    <a href="{{ path('app_crud_requetes_edit', {'id': requete.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<hr>
    <a href="" class="btn btn-primary">Print <span class="fa fa-print"></span></a>
</div>
{% endblock %}

templates/crud_requetes/new.html.twig
{% extends 'base_etudiant.html.twig' %}

{% block title %}New Requetes{% endblock %}

{% block body %}
<div>
    <h1>Create new Requetes</h1>

    {{ include('crud_requetes/_form.html.twig') }}

    <a href="{{ path('app_crud_requetes_index') }}">back to list</a>
</div>
{% endblock %}

templates/crud_requetes/show.html.twig
{% extends 'base_etudiant.html.twig' %}

{% block title %}Requetes{% endblock %}

{% block body %}
<div>
    <h1>Requetes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ requete.id }}</td>
            </tr>
            <tr>
                <th>Matiere</th>
                <td>{{requete.matiere.titre}}</td>
            </tr>
            <tr>
                <th>Recu</th>
                <td>{{ requete.recu }}</td>
            </tr>
            <tr>
                <th>Quitus</th>
                <td>{{ requete.quitus }}</td>
            </tr>
            <tr>
                <th>Objet</th>
                <td>{{ requete.objet }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ requete.description }}</td>
            </tr>
            <tr>
                <th>Date de depot</th>
                <td>{{ requete.dateDepot|date("d/m/Y H:i:s") }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ requete.etat }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ requete.statut }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_crud_requetes_index') }}">back to list</a>

    <a href="{{ path('app_crud_requetes_edit', {'id': requete.id}) }}">edit</a>

    {{ include('crud_requetes/_delete_form.html.twig') }}
</div>
{% endblock %}